include_guard(GLOBAL)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(CMAKE_CUDA_COMPILER)
  set(CMAKE_CUDA_STANDARD 17)
  set(CMAKE_CUDA_STANDARD_REQUIRED ON)
  set(CMAKE_CUDA_EXTENSIONS OFF)
endif()

option(RADAR_ENABLE_WARNINGS "Enable common compiler warnings" ON)
option(RADAR_ENABLE_STRICT_WARNINGS "Treat warnings as errors" OFF)
option(RADAR_ENABLE_CUDA_SEPARABLE_COMPILATION "Enable CUDA separable compilation" ON)

function(radar_apply_target_options target_name)
  get_target_property(_target_type "${target_name}" TYPE)
  if(NOT _target_type)
    message(FATAL_ERROR "Target '${target_name}' does not exist.")
  endif()

  if(_target_type STREQUAL "INTERFACE_LIBRARY")
    target_compile_features("${target_name}" INTERFACE cxx_std_17)
    return()
  endif()

  target_compile_features("${target_name}" PUBLIC cxx_std_17)

  if(RADAR_ENABLE_WARNINGS)
    if(MSVC)
      target_compile_options("${target_name}" PRIVATE /W4)
      if(RADAR_ENABLE_STRICT_WARNINGS)
        target_compile_options("${target_name}" PRIVATE /WX)
      endif()
    else()
      target_compile_options("${target_name}" PRIVATE -Wall -Wextra -Wpedantic)
      if(RADAR_ENABLE_STRICT_WARNINGS)
        target_compile_options("${target_name}" PRIVATE -Werror)
      endif()
    endif()
  endif()

  if(RADAR_ENABLE_CUDA_SEPARABLE_COMPILATION AND CMAKE_CUDA_COMPILER)
    set_target_properties("${target_name}" PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
  endif()
endfunction()
